language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: chalice deploy
env:
  secure: fll6KeDUXdsduOUkfFN6JFrw1Mstl3WQfCnLM1jx7JMV77DxuGbMwhocGA3/8xt8lal0870xrgMCSCJ8HtghIbxq7aYxiZ+yM8CPYGCGmd0p4yzBZhC//VTcpHZzuxmfX2stqL0O8PdWqm8N/BhmIUpWXjlrcGaAqy5H9g8+PotHvEbs9THh1LY0C1ou9oUQBkHYVl0ad8l21qaQYmCRwLllfatSn/ZZpVzygbmqJlYDuwgW6pkfY0OTRDUSwxXo86OKhbHemySwCKwcThnjB3WM1LZ68QA4X/gCLreJfAlXSuhBtMm6gLWsQieRQUvqmsBnA26l/gs7XoexVL/bYmx+f9LV9PzT3qncU6pK3twKzboI7pNEk8cx0vUj56cukeDQLUui5kCxnUvL3iQXYw6s844vQ7hHie0DiOV+dGJzd0ygdVl83OpQsL9Rph3e/PGwFjANlQ+eMbTROM0Mz6wwatULsmSMQzjo+BgNbUkpQ2nQM8PuqY+xY9rVe7CY8Op1PUHVI5OTlQ+sGGgs1GjPu9NAjGPBwfQyjsXZUSWKIpYXVwzEn9/GjyDYurzLwfRXwY/Iph35DxlurQqVvQDsOgBIHWsHsK7T2iJrJ++Gto0f28s+GM/18f0rG4Up99TJt4+LaacUXa0OTEHuLfZwnKrHSPRO9W0GMXwCmzM=
